### ISSUE TITLE
Problema en dependencia suds

### ISSUE THREAD

**Issue by pedroburon** [RaydelMiranda/django-oscar-webpay#2]
Trabajando en que el sdk de python de webpay funcionara me di cuenta que en vez de cambiar la librería suds puedes incluir la librería suds-jurko. Para py-wsse simplemente reescribí el plugin de suds.

**Comment by RaydelMiranda** [comment]
Saludos Pedro:

Si, estuve probando y tienes razón. Subiré el cambio proximanente.

**Comment by RaydelMiranda** [comment]
Ya estamos usando suds-jurko. Mucho mejor todo.

**Comment by pedroburon** [comment]
En Cornershop estuvimos trabajando en una versión más pythonica del sdk por si te interesa :)

Aún no está testeada en producción, pero funciona impeque.

https://github.com/cornershop/python-tbk

**Comment by RaydelMiranda** [comment]
Gracias, la miraré.
